# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Experiences' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Experiences

  target 'ExperiencesTests' do
    inherit! :search_paths
    # Pods for testing
pod "ScalingCarousel"

  end

  target 'ExperiencesUITests' do
    # Pods for testing
  end

end
